version: '3.8'

services:
  emqx:
    image: emqx/emqx:4.4.18
    container_name: dji-emqx
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8083:8083"
      - "8084:8084"
      - "18083:18083"
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=127.0.0.1
      - EMQX_AUTH__USER__1__USERNAME=JavaServer
      - EMQX_AUTH__USER__1__PASSWORD=123456
      - EMQX_LOG__LEVEL=debug
      - EMQX_LISTENER__WS__EXTERNAL=8083
      - EMQX_LISTENER__WS__EXTERNAL__PATH=/mqtt
      - EMQX_ALLOW_ANONYMOUS=true
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    restart: unless-stopped
    networks:
      - dji-network
    healthcheck:
      test: [ "CMD", "/opt/emqx/bin/emqx_ctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql:
    image: mysql:8.0
    container_name: dji-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloud_sample
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - ./sql/cloud_sample.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - dji-network

  redis:
    image: redis:7.0
    container_name: dji-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - dji-network

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8554:8554"   # RTSP (입출력)
      - "1935:1935"   # RTMP (입출력)
      - "8889:8889"   # HTTP (HLS + WebRTC/WHIP/WHEP)
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
volumes:
  mysql_data:
  redis_data:
  emqx_data:
  emqx_log:

networks:
  dji-network:
    driver: bridge
